services:
  - type: web
    name: acuhin-store
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: PORT
        value: 5000
      - key: VITE_API_URL
        value: /api
